name: 酋长之家
author: 酋长之家
#baseurl: ./
description: 技术成长之路
github1: https://lankors.github.io/
github2: https://www.heyyezi.com/
github3: https://baiyibing123.github.io/
github4: https://yx5198.github.io/
github5: http://taoyak.com/
github6: https://mingmings.org/
github7: https://successfuljian.github.io/
github8: https://nick-weixx.github.io/
github9: http://lezhimeng.coding.me/
github10: https://obeyconquer.github.io/
github11: https://dolinks.github.io/
github12: https://happyoldguys.github.io/
github13: https://fpp.coding.me/fpp/
email: good_decision@sina.com

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
